### ISSUE TITLE
Unable to Run After installing 

### ISSUE THREAD

**Issue by trprecht** [djfun/audio-visualizer-python#17]
I'm on Ubuntu 16.04.2. I installed the python and ffmpeg/avconv stuff, then I downloaded the code and trying `python3 main.py` and get the following

> Traceback (most recent call last):
  File "main.py", line 8, in <module>
    from PIL.ImageQt import ImageQt
  File "/usr/lib/python3/dist-packages/PIL/ImageQt.py", line 26, in <module>
    from PyQt5.QtGui import QImage, qRgba, QPixmap
RuntimeError: the PyQt5.QtCore and PyQt4.QtCore modules both wrap the QObject class

**Comment by IamDH4** [comment]
Hmm it looks like you have a conflict because PyQt5 is installed. PIL wants to use the QT5 libraries instead.

**Comment by djfun** [comment]
Can you try using pip to install pillow (at least version 3.3.0) as a replacement for python3-pil? (apt install python3-pil; pip3 install pillow)

> Fix for program importing PyQt4 when PyQt5 also installed #1942

 (https://github.com/python-pillow/Pillow/blob/master/CHANGES.rst#330-2016-07-01)

**Comment by IamDH4** [comment]
Stands to reason why we should probably look into packaging this with some dependencies, provided we workout the licensing.

**Comment by trprecht** [comment]
That did the trick! I've been able to make several videos now. Thanks!
