### ISSUE TITLE
Proper setuptools.py

### ISSUE THREAD

**Issue by ardeaf** [djfun/audio-visualizer-python#18]
Can you explain the logic behind the current setuptools.py file?  Looks like it was made to create an exe for windows but I'm not sure.  

Was looking to adjust setuptools and adjust the directory structure for proper python packaging so we can run the tool without doing "python main.py"

**Comment by djfun** [comment]
yes, the setup.py file was mainly for testing if it was possible to create an exe file for windows.

there is currently a major UI and app structure change going on (https://github.com/djfun/audio-visualizer-python/issues/15#issuecomment-304460449), so I don't think it makes much sense to change the directory structure here now. We are looking into possibilities to make it easier for people to use the software, for example by packaging it with some of the dependencies in some way, but we also need to consider the licensing.

**Comment by IamDH4** [comment]
Please see #28
