### ISSUE TITLE
Change Project and Preset Button Layouts

### ISSUE THREAD

**Issue by IamDH4** [djfun/audio-visualizer-python#25]
Need to add a `New Project` option. Perhaps this should all be contained within a dedicated `Project` button with a menu. Need to figure somthing out with presets. The user should be able to remove a preset without recalling it first.

![selection_054](https://user-images.githubusercontent.com/9543868/26854395-9aea30ae-4adb-11e7-8a3c-9936d78bf7a0.png)

**Comment by IamDH4** [comment]
Created a single button for Projects with several menu entries. Added New Project option, and created the function, but the function is not implemented yet.  Presets button, again created a function for it, but not implemented yet.
acf22900256d75c469c78efbd98139e3bfab0e93

![audio visualizer_076](https://user-images.githubusercontent.com/9543868/26897595-b32fe95c-4b8e-11e7-90a4-92ae150d48cd.png)

![audio visualizer_077](https://user-images.githubusercontent.com/9543868/26897600-b6a429cc-4b8e-11e7-92bf-51a93db601d3.png)

**Comment by tassaron2** [comment]
I created the preset manager using IamDH4's UI file. This update also includes displaying the loaded preset name next to a component name in the list, and showing an asterisk next to presets with modifications that haven't been saved.

bb1e54b31eb6157ef041764cfccd60484a0e02d8
4fc73f1e094289b50f828f0a3128d710e1d9ec4c
c51d86dd74c0548a0e81725534b78e23f6b6acaa
d3f979ef2461a3de701df0d5add545b80dfe23ad
59c2c090ab9275bc1146329536d43855a46d34f4
dbbefbf70ec9fad1735ee7199992ca6123bd54be
2ad14b7d6ca9216bcdc72c5e13937fcbccc887a3
