### ISSUE TITLE
Title text component options for nicer text

### ISSUE THREAD

**Issue by tassaron2** [djfun/audio-visualizer-python#29]
It would be easier to make nice-looking text on different background images if there were an option to add a stroke (outline) or drop-shadow to text. I would also like to see the ability to select extra font styles such as Small Caps, Bold, Oblique, and Italic.

**Comment by rikai** [comment]
In addition to text borders, it'd also be nice to be able to define the text border width.

**Comment by IamDH4** [comment]
The text component should also re-calculate it's position on a canvas size change. We had discussed in the path that we should perhaps store the position as a float and always calculate the pixel positions based on simple math.
```
xPosition = x / width     |    x = width * xPosition
yPosition = y / height    |    y = height * yPosition
```
If current Canvas size: 1280x720
Text Centered at: 640x374
```
0.5 = 640 / 1280
0.519444444 = 374 / 720
```

Resolution change to: 1920x1080
```
960 = 1920 * 0.5
560.99999952 = 1080 * 0.519444444
```
And round to the closest whole pixel:
`x = 960`  `y = 561`

**Comment by tassaron2** [comment]
Relative coords and center button: 5784cdbcf87556b61519782cd1fc27065ffbc631
Outline/stroke options and font style: 998f74149553ac7a9e27d7c85cebceda2ef32c64
Dropshadow option: 060a7dc2d263c0fd0e36e162943b8946df937bbd
