### ISSUE TITLE
Hotkeys

### ISSUE THREAD

**Issue by tassaron2** [djfun/audio-visualizer-python#31]
Please suggest any hotkeys you want in this issue.

Ones I'm thinking of right now:
`ctrl+s` Save Project
`ctrl+a` Save Project As
`ctrl+o` Open Project
`ctrl+n` New Project

`ctrl+t` Add Component (must use cursor keys & enter to pick a menu item)
`alt-enter` Focus Component List (navigate after focus with the tab key)

All the following hotkeys apply to the currently selected component:

`ctrl+shift+s` Save Preset
`ctrl+shift+o` Open Preset
`ctrl+shift+c` Clear Preset

`ctrl+up` Move Component Up
`ctrl+down` Move Component Down
`ctrl+home` Move Component to Top
`ctrl+end` Move Component to Bottom

`ctrl+r` Remove Component

**Comment by IamDH4** [comment]
Hotkeys implemented in 60d62599f785167f4c976a92fd8f19fbee4a363d

One Change:
`Ctrl+Space` Focus Component List
