### ISSUE TITLE
Update to Qt5

### ISSUE THREAD

**Issue by tassaron2** [djfun/audio-visualizer-python#33]
Last thing that needs to be done before packaging is an update to Qt5.8. Work on this is currently underway in the `feature-newgui-qt5` branch

**Comment by IamDH4** [comment]
`feature-newgui-qt5` appears to be fully functional. Squashed in 3 commits. Thanks for the assist @tassaron2!  I'll leave it overnight, if you don't find any bugs feel free to merge back into `feature-newgui` and close this issue.

e92e9d79f95ad67e83074ef318278c3486601eac
680214f5180a12f2250d8e266df9375ce99b9f80
83d55593d005cd540b042b27e6141a3d506d4215

**Comment by tassaron2** [comment]
Looks good to me.
