### ISSUE TITLE
Can't push project. 

### ISSUE THREAD

**Issue by mspeers** [djfun/audio-visualizer-python#37]
I have finish off new video size hight, width. I can't push the new branch to the do pull on it to master

**Comment by tassaron2** [comment]
See [GitHub's Guide](https://guides.github.com/activities/forking/) for information on how to contribute by forking and making a pull request. However make note that the latest version is being developed in the `feature-newgui` branch, so new pull requests should be forked from that.

**Comment by IamDH4** [comment]
Closing this issue, this is not a problem with the software.
