### ISSUE TITLE
Progress bar doesn't show text on macOS

### ISSUE THREAD

**Issue by rikai** [djfun/audio-visualizer-python#39]
Tested on Sierra.

![An example](https://user-images.githubusercontent.com/515221/27520518-72029df2-59c2-11e7-9312-d8a5a310067d.png)

It's my understanding that on other OSes this progress bar contains the status of the encode.

**Comment by tassaron2** [comment]
Added an extra label to show video export status on Mac while exporting. It appears centred beneath the progress bar. 0c394d77e388adb91beee210a9b66652db9d17cb
