### ISSUE TITLE
Non-native disabled listbox on macOS

### ISSUE THREAD

**Issue by rikai** [djfun/audio-visualizer-python#40]
Unlike the rest of the components, the disabled listbox looks non-native, may want to look into this to see if there's anything that can be done to make it look nicer.

![non-native listbox](https://user-images.githubusercontent.com/515221/27520543-c87ad87a-59c2-11e7-8708-0ebb2f2906e2.png)

**Comment by tassaron2** [comment]
7b6ef6349b1922e71ab83fc45d4a1598ef203511
0c394d77e388adb91beee210a9b66652db9d17cb

Component list is left enabled on Mac and signals blocked to achieve same practical effect.
