### ISSUE TITLE
Relative positioning and dimensions for everything

### ISSUE THREAD

**Issue by tassaron2** [djfun/audio-visualizer-python#44]
Currently changing the output resolution drastically changes the video due to absolute positioning being used by components everywhere. Only the scaling options are relative. If we change all components to use relative positioning, then changing the output resolution will not affect the appearance of the video. Thus someone can export at different resolutions using the same project file.

We should make all components use floats to define their positions as suggested by @IamDH4 [in #29](https://github.com/djfun/audio-visualizer-python/issues/29#issuecomment-310971203). We can use either spinboxes with percentages or sliders in the GUI instead of the current text inputs.

**Comment by IamDH4** [comment]
Just to be clear I think pixel values should still be used in the UI, and the conversion to floats should be handled behind the scenes. With values in the UI updating on a resolution change.

**Comment by tassaron2** [comment]
As of 5784cdbcf87556b61519782cd1fc27065ffbc631, components can define 'relative widgets' which will have their pixel values updated when the resolution is changed. This is applied to every component's x, y, width, height, and font size. So this issue is now closed.
