### ISSUE TITLE
No module named 'PyQt4'

### ISSUE THREAD

**Issue by ilyasst** [djfun/audio-visualizer-python#58]
Hi,

I have followed all the steps and currently have a python3 virtual environment inside which I am trying to run main.py
I keep getting this error
```
Traceback (most recent call last):
  File "main.py", line 2, in <module>
    from PyQt4 import QtCore, QtGui, uic
ImportError: No module named 'PyQt4'
```
Even if I have Py-Qt4 installed.
I've tried several times and cannot solve it.

Could you please help me with this ?

Thanks,
Ilyass

**Comment by djfun** [comment]
Hi,
which OS/Version are you using? Also: you might want to try to use the feature-newgui branch (`git checkout feature-newgui`), which uses Qt5.

**Comment by ilyasst** [comment]
Hi, 

I am using Ubuntu 16.04.3 LTS.
I will try the feature-newgui branch and I'll report back to you !

Cheers

**Comment by Heath3827** [comment]
It is a dependantcy error. Ensure you have libqt4 installed and when you launch Audio Visualiser you must type "python3 main.py" otherwise it won't work.

**Comment by davideuler** [comment]
Hi, you just need to use PyQt5 instead. Some codes need to be changed for API changes in PyQt5.
I've created a pull request at: https://github.com/djfun/audio-visualizer-python/pull/60

Also, you can use this fork:
https://github.com/ihopeit/audio-visualizer-python

**Comment by GingkathFox** [comment]
I have the same issue on MacOS. Running:
MacOS High Sierra 10.13.3

**Comment by ilyasst** [comment]
Sorry I never reported back on this issue.

I did as @djfun suggested and installed PyQT5, I then started avp using the `avp` command after loading my virtual env, it workerd fine.
