### ISSUE TITLE
TypeError - video_thread.py tries to join a string and an int

### ISSUE THREAD

**Issue by ezr** [djfun/audio-visualizer-python#63]
Hello, 
In the GUI I picked the classic visualizer. Gave it an mp3. When I hit "Create Video" the program crashed with the message:

```
Traceback (most recent call last):
  File "/home/user/py/env/avp/lib/python3.6/site-packages/avpython/video_thread.py", line 250, in createVideo
    cmd = " ".join(ffmpegCommand)
TypeError: sequence item 13: expected str instance, int found
Aborted (core dumped)
```

Adding these lines to video_thread.py fixed the issue (right before "cmd = " ".join(ffmpegCommand)":
```
        i = 0
        while i < len(ffmpegCommand):
            ffmpegCommand[i] = str(ffmpegCommand[i])
            i += 1
```
With that change the program works as expected. Thanks.

**Comment by tassaron** [comment]
Thanks for reporting this, and sorry it took so long to respond.

I have fixed this bug in 1fda5fbe8121f15f7a6e13ddedefb0cf07ae5d48
