### ISSUE TITLE
Color issue

### ISSUE THREAD

**Issue by ExperiBass** [djfun/audio-visualizer-python#64]
When I click the box by the text that says `Visualizer:`, AVP crashes with this message:
```css
Traceback (most recent call last):
  File "main.py", line 172, in <lambda>
    window.pushButton_visColor.clicked.connect(lambda: self.pickColor('vis'))
  File "main.py", line 307, in pickColor
    color = QtGui.QColorDialog.getColor()
AttributeError: module 'PyQt5.QtGui' has no attribute 'QColorDialog'
Abort trap: 6
```

**Comment by the7erm** [comment]
I'm having the same issue.

**Comment by tassaron** [comment]
Ah, it seems they moved QColorDialog from QtGui into QtWidgets. The equivalent line of code in v2 of the application is [here](https://github.com/djfun/audio-visualizer-python/blob/893c10c6ca8b7a9c04b9aaa086a46503166c880b/src/component.py#L632).

The project is no longer dormant and I am currently working on the stability of v2 so it can be merged into the main (master) branch. Sorry for letting you down! For what it's worth, I'm now making a firm commitment to this project. I'll respond to any future issues within 48 hours.
