### ISSUE TITLE
Changing the location of the visual effects

### ISSUE THREAD

**Issue by naddeoa** [djfun/audio-visualizer-python#65]
I wanted to get your input on how much work it would be to change the location of the visual effects? I was hoping to move the bars to the bottom of the display and remove the bottom row. Is this possible, and if so, which file should I look in?

Thanks for creating the script!

**Comment by tassaron2** [comment]
You could try installing the new-gui branch of the program: https://github.com/djfun/audio-visualizer-python/tree/feature-newgui

In that branch, the visualizer has an option to only show bars coming up from the bottom of the frame. You can also change the intensity of the effect and the y-offset for a more precise placement. The GUI is completely different but hopefully easy to understand.

Alternatively, it's probably easy enough to edit the script you're currently using. I *think* deleting line 105 from `core.py` would do the trick.
