### ISSUE TITLE
An Appimage version of the appliacation

### ISSUE THREAD

**Issue by AlaOnline** [djfun/audio-visualizer-python#67]
An Appimage version of the application that include all the dependencies .

**Comment by tassaron** [comment]
I agree that an AppImage would be good to have. I don't know how to make it myself, but it is something we've discussed in #28. If you have more feedback, use that issue instead.

Please note: Help would be appreciated in creating an AppImage (or any other package format). I'm planning to merge the `feature-newgui` branch eventually, so please use that branch if you want to help. Don't use the main (master) branch.
