### ISSUE TITLE
windows requirements.txt? for pip install

### ISSUE THREAD

**Issue by Roboxkin** [djfun/audio-visualizer-python#79]
Hello?
Please write installation instructions for windows.
pip install? 

---python
Suggestion [3,General]: The command setup.py was not found, but exists in the current location. By default, Windows PowerShell does not load commands from the current location. If you are sure you trust a command, type ".\setup.py". For more information, see "get-help about_Command_Precedence".
(.venv) PS D:\clips> avp
avp : The name "avp" is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling and the existence and validity of the path, then try again.
line:1 character:1
+avp
+ ~~~
 + CategoryInfo : ObjectNotFound: (avp:String) [], CommandNotFoundException
 + FullyQualifiedErrorId : CommandNotFoundException

(.venv) PS D:\clips> python -m avp
D:\clips\.venv\Scripts\python.exe: No module named avp
(.venv) PS D:\clips>
---

**Comment by tassaron** [comment]
`pip install .` installs using the provided setup.py file. The dot tells it to use the current folder so you have to run it within the folder with setup.py
